### ISSUE TITLE
/tmp/winery permission error

### ISSUE THREAD

**Issue by hnicke** [eclipse/winery#193]
I tried to use the yaml parser in our TOSCAna project and hit some IO errors.

#### What happened
1. execute code as user `user1` (was `root` but shouldn't matter)
2. execute code as user `user2`.
- while running project with `user2`, program tries to modify `/tmp/winery/normative_file/tosca_simple_yaml_1_1.yml`
- this file is owned by `user1`, file permissions are `644`

#### Possible fixes
- Change permissions of tmp files to `666`
- ~~Cleanup tempdir~~ not a solution, if jvm crashes before cleanup
- Use different tmpdir each run or for every user. E.g. use the File.getTempDir() mechanisms

Stacktrace:
```
19:14:37.642 [main] DEBUG org.eclipse.winery.yaml.common.reader.yaml.Builder Read Service Template: /var/lib/jenkins/workspace/toscana/core/testsuite-spring-tmpdir/simple-taskcsar/content/template.yaml
19:14:37.701 [main] DEBUG org.eclipse.winery.repository.backend.filebased.FileUtils Could not delete file
19:14:37.703 [main] DEBUG org.eclipse.winery.repository.backend.filebased.FileUtils Could not delete dir
java.nio.file.DirectoryNotEmptyException: /tmp/winery/normative_file
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.eclipse.winery.repository.backend.filebased.FileUtils$1.postVisitDirectory(FileUtils.java:60)
	at org.eclipse.winery.repository.backend.filebased.FileUtils$1.postVisitDirectory(FileUtils.java:44)
	at java.nio.file.Files.walkFileTree(Files.java:2688)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.eclipse.winery.repository.backend.filebased.FileUtils.forceDelete(FileUtils.java:44)
	at org.eclipse.winery.yaml.common.Utils.deleteTmpDir(Utils.java:101)
	at org.eclipse.winery.yaml.common.Utils.getTmpDir(Utils.java:91)
	at org.eclipse.winery.yaml.common.validator.ImportVisitor.visit(ImportVisitor.java:43)
	at org.eclipse.winery.yaml.common.validator.TypeValidator.validate(TypeValidator.java:50)
	at org.eclipse.winery.yaml.common.validator.Validator.validate(Validator.java:40)
	at org.eclipse.winery.yaml.common.reader.yaml.Reader.readServiceTemplate(Reader.java:141)
	at org.eclipse.winery.yaml.common.reader.yaml.Reader.parse(Reader.java:44)
	at org.opentosca.toscana.core.parse.CsarParseServiceImpl.parse(CsarParseServiceImpl.java:29)
	at org.opentosca.toscana.plugins.k8s.K8sPluginTest.validTServiceTemplate(K8sPluginTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:16)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
java.nio.file.AccessDeniedException: /tmp/winery/normative_file/tosca_simple_yaml_1_1.yml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at java.nio.file.Files.copy(Files.java:3004)
	at org.eclipse.winery.yaml.common.validator.ImportVisitor.visit(ImportVisitor.java:45)
	at org.eclipse.winery.yaml.common.validator.TypeValidator.validate(TypeValidator.java:50)
	at org.eclipse.winery.yaml.common.validator.Validator.validate(Validator.java:40)
	at org.eclipse.winery.yaml.common.reader.yaml.Reader.readServiceTemplate(Reader.java:141)
	at org.eclipse.winery.yaml.common.reader.yaml.Reader.parse(Reader.java:44)
	at org.opentosca.toscana.core.parse.CsarParseServiceImpl.parse(CsarParseServiceImpl.java:29)
	at org.opentosca.toscana.plugins.k8s.K8sPluginTest.validTServiceTemplate(K8sPluginTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at 
```

**Comment by hnicke** [comment]
Resolved with #197
