### ISSUE TITLE
A couple of issues while editing a topology template

### ISSUE THREAD

**Issue by Roberto-Mameli** [eclipse/winery#729]
Hi all,

I wonder if this tool is still actively supported by the community.

I'm trying to create a topology template by means of Winery. I'm using the latest docker image (*docker pull opentosca/winery:latest*) and I'm experiencing a couple of problems with the editor:

- first, I'm not able to edit the license in the LICENSE file (simply, there is no Save button in the tab)
- second, some node_types may be dragged and dropped to the canvas, some other not, apparently without reason

Is anyone experiencing the same issues? I tryed with 2 different browsers on Ubuntu (Firefox and Chromium), and also with 2 different browsers on Windows (Firefox and Chrome), same story.

Is there anyone that can help?

Thank you in advance
Roberto

**Comment by lharzenetter** [comment]
Hi Roberto,

do you want to edit a license file of an existing Definition, i.e., Node Type, Artifact Template, ...? As they are versioned, they are not editable by default. You can, however, disable the enforced versioning by disabling the feature under Admin and Configuration.

Regarding the modeling in the Topology Modeler: I do not know what's the issue there. Are you modeling in XML or YAML mode?

Cheers
Lukas

**Comment by Roberto-Mameli** [comment]
Hi Lukas,

thank you for the quick response.

Regarding the license file, I was trying to add a new service template (let's say testServiceTemplate). I just specify the name, nothing else (e.g. I use the default targetNamespace). When the service template is created, I'm able to edit and save text in the README tab, but when I try to add a new license in the LICENSE tab, it happens that I can write anything I want, but there is no way to save it. Is there something I'm missing here? This problem is not blocking, since it can be easily circumvented by simply putting the license file in the proper place in the repository, but it would be nice to do this directly from the interface.

Coming to the second issue, this is actually blocking, since I'm trying to design some YAML service templates, but I do not succeed. Actually there is a bunch of node_types that cannot be dragged and dropped on the canvas, i.e. they cannot be used in the design.

I add a further detail, that is probably important. I'm not using RADON type definitions. I'm using a repository built through a self made tool, which parses yaml definitions and uses them to organize information according to the directory structure required by Winery. I used this tool to build a repository with all normative and non-normative TOSCA types (v1.3), as well as ETSI NFV SOL0001 types.
This indeed could be the problem, even if I do not understand why.... all types in input yaml files are correctly parsed by the tool and successfully imported in Winery, I can see all of them in the list of available node_types, data_types, relationship_types, etc.. However, when I try to design a service template, some of them cannot be used, When I click on one such element in the palette on the left of the screen, this is the error that appears in the Developer Tools window on the right:

>main.807cf6d047894bb9c8d2.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'serviceTemplateOrNodeTypeOrNodeTypeImplementation')
>    at t.getDefaultPropertiesFromEntityTypes (main.807cf6d047894bb9c8d2.js:1:21208)
>    at t.generateIdTypeAndProperties (main.807cf6d047894bb9c8d2.js:1:1254523)
>    at t.generateNewNode (main.807cf6d047894bb9c8d2.js:1:1253878)
>    at t.generateNewNodeFromMouseEvent (main.807cf6d047894bb9c8d2.js:1:1253731)
>    at Object.handleEvent (main.807cf6d047894bb9c8d2.js:1:1259176)
>    at Object.handleEvent (main.807cf6d047894bb9c8d2.js:1:1906420)
>    at Object.handleEvent (main.807cf6d047894bb9c8d2.js:1:1917603)
>    at Vp (main.807cf6d047894bb9c8d2.js:1:1876140)
>    at main.807cf6d047894bb9c8d2.js:1:1882416
>    at HTMLDivElement.<anonymous> (main.807cf6d047894bb9c8d2.js:1:2144817)

Does this suggest anything to you?

Thank you very much for your help

Regards
Roberto

P.S. in my opinion, both the tool I was mentioning above, and the repository I've obtained through it (the one I'm trying to use now) might be interesting for the community. In the next days I will probably release them as open source. If you are interested I will share the links on github as soon as available.

**Comment by Roberto-Mameli** [comment]
Hello Lukas,

maybe I found the issue. It should be due to some inconsistent data from input yaml files I imported.

As I said in my previous message, I'm using a custom tool to extract definitions from a bunch of yaml files and to import them into Winery. The first time I used input files from:

[https://github.com/oasis-open/tosca-community-contributions.git/profiles/org.oasis-open/simple/1.3](https://github.com/oasis-open/tosca-community-contributions.git/profiles/org.oasis-open/simple/1.3)
[https://github.com/oasis-open/tosca-community-contributions.git/profiles/org.oasis-open/non-normative](https://github.com/oasis-open/tosca-community-contributions.git/profiles/org.oasis-open/non-normative)
[https://forge.etsi.org/rep/nfv/SOL001](https://forge.etsi.org/rep/nfv/SOL001)

and I experienced the problem in the topology modeler, with some nodes that cannot be selected from the palette.

Now I have tried again yaml import, this time using only normative types (first link) and etsi types (third link). If I launch the Winery topology modeler without importing OASIS non normative types, I see that everything is working. I guess that non normative types either refer to some entity which is not correctly defined or which is redefined. In other words, the problem seems neither in the Winery topology modeler, nor in the tool used to extract the information. It's just a matter of dirty input data.

The issue of the license (i.e. the inability to edit the license for a newly created service template) is still present. I don't know if this is my fault as well :-)

Thanks
Roberto

**Comment by lharzenetter** [comment]
Okay, nice - what you can do also have the etsi elements in there, you can try to model them yourself using Winery. As Winery's model is standard conform, extension elements are usually not supported out of the box. However, if you can model them using the standard conform syntax, it should work correctly.

Regarding the License file: If you want to investigate it further you can have a look into the UI code. You can run the UI locally and use the Docker Container as the backend. In development mode, it simply expects the Winery backend to be available on port 8080.

Cheers
Lukas

**Comment by Roberto-Mameli** [comment]
Hi Lukas,

thank you for suggestion. I take the chance to notify you that I have just released a contribution on the OASIS TOSCA Community Contribution page on Github:

https://github.com/oasis-open/tosca-community-contributions/tree/master/tools/winery-canvas/tosca1.3_etsinfv4.4.1

It consists in a folder organized according to Winery's repository structure, which provides all relevant type definitions from OASIS TOSCA Normative types (aligned with TOSCA Simple Profile in YAML Version 1.3) and ETSI NFV SOL001 types (VNFD, PNFD and NSD descriptions compliant with TOSCA Specification).

I will soon release to the Open Source Community another contribution, specifically the Linux command line tool that I have used to parse input yaml file descriptors and to organize them into a Winery suitable directory structure. This will be available soon at the following link:

https://github.com/Engineering-Research-and-Development/importToscaDescWinery

If you think it might be useful, feel free to use and share the contributions above as you need.

Thank you
Roberto
