### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by godelc7** [eclipse/winery#757]
When building the docker image with `docker build -t winery .` , I got build errors. The corresponding terminal output is below. Is it possible that I'm doing something wrong?

```
253.9 [INFO] Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.60/kotlin-stdlib-common-1.3.60.jar (171 kB at 46 kB/s)
254.0 [INFO] Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.61/kotlin-stdlib-jdk8-1.3.61.jar (15 kB at 4.0 kB/s)
254.1 [INFO] Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar (47 kB at 12 kB/s)
254.2 [INFO] Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime/0.14.0/kotlinx-serialization-runtime-0.14.0.jar (497 kB at 124 kB/s)
254.3 [INFO] Solidity: adding to process 'authorization.sol'
254.3 [INFO] Solidity: adding to process 'provenance.sol'
269.4 Solidity version 0.4.26 is not installed. Downloading and installing it to ~/.web3j/solc/0.4.26
284.4 [INFO] ------------------------------------------------------------------------
284.4 [INFO] Reactor Summary for Winery 3.0.0-SNAPSHOT:
284.4 [INFO] 
284.4 [INFO] Winery ............................................. SUCCESS [ 16.548 s]
284.4 [INFO] org.eclipse.winery.common .......................... SUCCESS [02:49 min]
284.4 [INFO] org.eclipse.winery.model.csar.toscametafile ........ SUCCESS [  9.243 s]
284.4 [INFO] org.eclipse.winery.accountability .................. FAILURE [01:21 min]
284.4 [INFO] org.eclipse.winery.model.bpmn4tosca ................ SKIPPED
284.4 [INFO] org.eclipse.winery.bpmn4tosca.converter.tobpel ..... SKIPPED
284.4 [INFO] org.eclipse.winery.model.extension ................. SKIPPED
284.4 [INFO] org.eclipse.winery.model ........................... SKIPPED
284.4 [INFO] org.eclipse.winery.model.tosca.canonical ........... SKIPPED
284.4 [INFO] org.eclipse.winery.model.tosca.yaml ................ SKIPPED
284.4 [INFO] org.eclipse.winery.model.tosca.xml ................. SKIPPED
284.4 [INFO] org.eclipse.winery.repository ...................... SKIPPED
284.4 [INFO] org.eclipse.winery.tools.copybaragenerator ......... SKIPPED
284.4 [INFO] org.eclipse.winery.cli ............................. SKIPPED
284.4 [INFO] org.eclipse.winery.topologygraph ................... SKIPPED
284.4 [INFO] org.eclipse.winery.compliance ...................... SKIPPED
284.4 [INFO] org.eclipse.winery.crawler ......................... SKIPPED
284.4 [INFO] org.eclipse.winery.edmm ............................ SKIPPED
284.4 [INFO] org.eclipse.winery.highlevelrestapi ................ SKIPPED
284.4 [INFO] org.eclipse.winery.generators.ia ................... SKIPPED
284.4 [INFO] org.eclipse.winery.model.adaptation ................ SKIPPED
284.4 [INFO] org.eclipse.winery.model.threatmodeling ............ SKIPPED
284.4 [INFO] org.eclipse.winery.repository.rest ................. SKIPPED
284.4 [INFO] org.eclipse.winery.repository.client ............... SKIPPED
284.4 [INFO] org.eclipse.winery.tools.deployablecomponents ...... SKIPPED
284.4 [INFO] org.eclipse.winery.reporting ....................... SKIPPED
284.4 [INFO] org.eclipse.winery.frontends ....................... SKIPPED
284.4 [INFO] ------------------------------------------------------------------------
284.4 [INFO] BUILD FAILURE
284.4 [INFO] ------------------------------------------------------------------------
284.4 [INFO] Total time:  04:41 min
284.4 [INFO] Finished at: 2024-08-02T07:43:00Z
284.4 [INFO] ------------------------------------------------------------------------
284.5 [ERROR] Failed to execute goal org.web3j:web3j-maven-plugin:4.8.7:generate-sources (generate-sources) on project org.eclipse.winery.accountability: Could not compile Solidity files
284.5 [ERROR] java.net.UnknownHostException: github.com
284.5 [ERROR]   at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
284.5 [ERROR]   at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
284.5 [ERROR]   at java.base/java.net.Socket.connect(Socket.java:633)
284.5 [ERROR]   at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
284.5 [ERROR]   at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
284.5 [ERROR]   at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
284.5 [ERROR]   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
284.5 [ERROR]   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
284.5 [ERROR]   at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
284.5 [ERROR]   at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
284.5 [ERROR]   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
284.5 [ERROR]   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
284.5 [ERROR]   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
284.5 [ERROR]   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
284.5 [ERROR]   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
284.5 [ERROR]   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
284.5 [ERROR]   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
284.5 [ERROR]   at java.base/java.net.URL.openStream(URL.java:1161)
284.5 [ERROR]   at kotlin.io.TextStreamsKt.readBytes(ReadWrite.kt:150)
284.5 [ERROR]   at org.web3j.sokt.SolcInstance.install(SolcInstance.kt:65)
284.5 [ERROR]   at org.web3j.mavenplugin.solidity.SolidityCompiler.getSolcProcessFromSokt(SolidityCompiler.java:78)
284.5 [ERROR]   at org.web3j.mavenplugin.solidity.SolidityCompiler.compileSrc(SolidityCompiler.java:51)
284.5 [ERROR]   at org.web3j.mavenplugin.JavaClassGeneratorMojo.parseSoliditySources(JavaClassGeneratorMojo.java:280)
284.5 [ERROR]   at org.web3j.mavenplugin.JavaClassGeneratorMojo.processSolidityFile(JavaClassGeneratorMojo.java:176)
284.5 [ERROR]   at org.web3j.mavenplugin.JavaClassGeneratorMojo.processSolidityFiles(JavaClassGeneratorMojo.java:208)
284.5 [ERROR]   at org.web3j.mavenplugin.JavaClassGeneratorMojo.execute(JavaClassGeneratorMojo.java:192)
284.5 [ERROR]   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
284.5 [ERROR]   at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
284.5 [ERROR]   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
284.5 [ERROR]   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
284.5 [ERROR]   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
284.5 [ERROR]   at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
284.5 [ERROR]   at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
284.5 [ERROR]   at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
284.5 [ERROR]   at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
284.5 [ERROR]   at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
284.5 [ERROR]   at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
284.5 [ERROR]   at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
284.5 [ERROR]   at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
284.5 [ERROR]   at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
284.5 [ERROR]   at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
284.5 [ERROR]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
284.5 [ERROR]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
284.5 [ERROR]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
284.5 [ERROR]   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
284.5 [ERROR]   at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
284.5 [ERROR]   at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
284.5 [ERROR]   at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
284.5 [ERROR]   at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
284.5 [ERROR] -> [Help 1]
284.5 [ERROR] 
284.5 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
284.5 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
284.5 [ERROR] 
284.5 [ERROR] For more information about the errors and possible solutions, please read the following articles:
284.5 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
284.5 [ERROR] 
284.5 [ERROR] After correcting the problems, you can resume the build with the command
284.5 [ERROR]   mvn <args> -rf :org.eclipse.winery.accountability
------

 54 warnings found (use --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
 - LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 13)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 15)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 16)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 17)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 18)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 19)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 20)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 21)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 22)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 23)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 24)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 25)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 26)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 27)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 28)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 29)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 30)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 31)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 32)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 33)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 34)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 35)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 36)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 37)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 38)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 39)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 40)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 41)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 42)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 43)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 44)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 45)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 46)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 47)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 48)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 49)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 50)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 51)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 52)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 53)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 54)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 55)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 56)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 57)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 58)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 59)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 60)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 61)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 62)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 63)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 64)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 65)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 66)
Dockerfile:10
--------------------
   8 |     COPY . /tmp/winery
   9 |     WORKDIR /tmp/winery
  10 | >>> RUN mvn package -DskipTests=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -B
  11 |     
  12 |     FROM tomcat:9-jdk17-openjdk-buster
--------------------
ERROR: failed to solve: process "/bin/sh -c mvn package -DskipTests=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -B" did not complete successfully: exit code: 1
```

**Comment by godelc7** [comment]
Turned out that it was an error in my proxy settings
